# Generated by Django 4.2.10 on 2024-02-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='progress_reports',
            field=models.ManyToManyField(blank=True, to='tasks.progressreport'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
