# Generated by Django 4.2.10 on 2024-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_progressreport_team_remove_team_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
